# Generated by Django 3.2.8 on 2021-12-30 14:17

from django.db import migrations, models
import voucher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('emailAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=voucher.models.increment_voucher_number, max_length=100, unique=True)),
                ('facility_name', models.CharField(blank=True, max_length=500, null=True)),
                ('number_of_adults', models.CharField(default='0', max_length=100)),
                ('number_of_children', models.CharField(default='0', max_length=100)),
                ('children_age', models.CharField(blank=True, max_length=500, null=True)),
                ('infants', models.CharField(blank=True, max_length=500, null=True)),
                ('baby_cot', models.CharField(blank=True, max_length=500, null=True)),
                ('accomodation', models.CharField(blank=True, max_length=500, null=True)),
                ('meal_plan', models.CharField(blank=True, max_length=500, null=True)),
                ('extras_to', models.CharField(blank=True, max_length=500, null=True)),
                ('special_instructions', models.CharField(blank=True, max_length=500, null=True)),
                ('reserver_name', models.CharField(blank=True, max_length=500, null=True)),
                ('reservation_date', models.CharField(blank=True, max_length=500, null=True)),
                ('client_name', models.CharField(blank=True, max_length=500, null=True)),
                ('client_email', models.CharField(blank=True, max_length=500, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
