# Generated by Django 3.2.8 on 2021-12-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='reservation_date',
            field=models.DateField(blank=True, max_length=500, null=True),
        ),
    ]
