# Generated by Django 3.2.8 on 2022-01-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20211230_1717'),
        ('voucher', '0002_alter_voucher_reservation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='accomodation',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='meal_plan',
        ),
        migrations.AddField(
            model_name='voucher',
            name='ai',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='bb',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.client'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='double',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='fb',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='hb',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='number_of_nights',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='single',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='triple',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='twin',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
