# Generated by Django 3.2.8 on 2022-01-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_voucher_accommodation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('EMAIL_SENT', 'EMAIL_SENT'), ('MODIFIED', 'MODIFIED')], default='NEW', max_length=19),
        ),
    ]
