# Generated by Django 3.2.8 on 2022-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_alter_voucher_voucher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_status',
            field=models.CharField(blank=True, choices=[('CANCELLED', 'CANCELLED'), ('EMAIL_SENT', 'EMAIL_SENT'), ('MODIFIED', 'MODIFIED'), ('NEW', 'NEW')], default='NEW', max_length=19, null=True),
        ),
    ]
