# Generated by Django 3.2.8 on 2021-10-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20211015_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='addressLine1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='taxNumber',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='taxNumber',
        ),
    ]
