# Generated by Django 3.2.8 on 2021-10-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20211028_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, default='Kshs', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
