# Generated by Django 3.2.8 on 2021-10-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_product_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.AlterUniqueTogether(
            name='invoiceproduct',
            unique_together={('invoice', 'product')},
        ),
    ]
