# Generated by Django 3.2.8 on 2021-10-29 12:20

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20211029_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(default=invoice.models.increment_invoice_number, max_length=100, unique=True),
        ),
    ]
