# Generated by Django 3.2.8 on 2021-10-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, choices=[('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Kitale', 'Kitale'), ('Nakuru', 'Nakuru')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, choices=[('Hotel', 'Hotel'), ('Accommodation', 'Accommodation'), ('Excursions', 'Excursions'), ('Air Ticket', 'Air Ticket'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
