# Generated by Django 3.2.8 on 2021-11-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_paymentterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('15 days', '15 days'), ('30 days', '30 days')], default='15 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, choices=[('Accommodation/Hotel', 'Accommodation/Hotel'), ('Conference', 'Conference'), ('Excursions', 'Excursions'), ('Air Ticket', 'Air Ticket'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
