# Generated by Django 3.2.8 on 2021-11-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20211109_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='istaxable',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
