# Generated by Django 3.2.8 on 2022-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20211230_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
